# Generated by Django 4.2.5 on 2023-11-27 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0002_juegotemporal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegotemporal',
            name='jugador',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='juegotemporal',
            name='puntaje',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_respuesta', models.CharField(max_length=255)),
                ('puntaje_asociado', models.IntegerField()),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_app.pregunta')),
            ],
        ),
    ]
