# Generated by Django 4.2.5 on 2023-11-27 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0003_alter_juegotemporal_jugador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JugadorTemporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('puntaje', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Jugador',
            new_name='JugadorPermanente',
        ),
        migrations.RenameField(
            model_name='juegotemporal',
            old_name='pregunta',
            new_name='pregunta_actual',
        ),
        migrations.RenameField(
            model_name='juegotemporal',
            old_name='puntaje',
            new_name='puntaje_acumulado',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='puntaje_buena',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='puntaje_mala',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='puntaje_media',
            field=models.IntegerField(default=2),
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.AlterField(
            model_name='juegotemporal',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trivia_app.jugadortemporal'),
        ),
    ]
