# Generated by Django 4.2.5 on 2023-11-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0005_delete_juegotemporal'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaAlta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=255)),
                ('opcion_mala', models.CharField(max_length=100)),
                ('puntaje_mala', models.IntegerField(default=1)),
                ('opcion_media', models.CharField(max_length=100)),
                ('puntaje_media', models.IntegerField(default=2)),
                ('opcion_buena', models.CharField(max_length=100)),
                ('puntaje_buena', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=255)),
                ('opcion_mala', models.CharField(max_length=100)),
                ('puntaje_mala', models.IntegerField(default=1)),
                ('opcion_media', models.CharField(max_length=100)),
                ('puntaje_media', models.IntegerField(default=2)),
                ('opcion_buena', models.CharField(max_length=100)),
                ('puntaje_buena', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=255)),
                ('opcion_mala', models.CharField(max_length=100)),
                ('puntaje_mala', models.IntegerField(default=1)),
                ('opcion_media', models.CharField(max_length=100)),
                ('puntaje_media', models.IntegerField(default=2)),
                ('opcion_buena', models.CharField(max_length=100)),
                ('puntaje_buena', models.IntegerField(default=3)),
            ],
        ),
    ]
