# Generated by Django 4.2.5 on 2023-11-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0006_preguntaalta_preguntabaja_preguntamedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadortemporal',
            name='PutanjeRonda',
            field=models.IntegerField(default=0),
        ),
    ]
