# Generated by Django 4.2.5 on 2023-11-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0007_jugadortemporal_putanjeronda'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadortemporal',
            name='Bool',
            field=models.CharField(default='True', max_length=50),
        ),
    ]
