# Generated by Django 4.2.5 on 2023-11-29 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0008_jugadortemporal_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadortemporal',
            name='Bool',
            field=models.IntegerField(default=1),
        ),
    ]
