# Generated by Django 4.2.5 on 2023-11-29 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0009_alter_jugadortemporal_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadortemporal',
            name='Bool',
            field=models.CharField(default='True', max_length=50),
        ),
    ]
