# Generated by Django 4.2.5 on 2023-11-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia_app', '0010_alter_jugadortemporal_bool'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadortemporal',
            name='Salvidas',
            field=models.IntegerField(default=3),
        ),
    ]
